-- 为 tasks 表添加 stdout/stderr 输出字段和进度字段
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS stdout TEXT DEFAULT '';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS stderr TEXT DEFAULT '';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS progress INT DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS progress_message VARCHAR(500) DEFAULT '';
