-- 添加机器外映射配置字段（Nginx/端口映射）
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS external_ip VARCHAR(64) DEFAULT '';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS external_ssh_port INT DEFAULT 0;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS external_jupyter_port INT DEFAULT 0;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS external_vnc_port INT DEFAULT 0;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS nginx_domain VARCHAR(255) DEFAULT '';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS nginx_config_path VARCHAR(500) DEFAULT '';
